alloy:
  configMap:
    content: |
      // Scrape Grafana Operator Metrics
      prometheus.scrape "grafana_operator" {
        targets = [
          {
            "__address__" = "grafana-operator-metrics-service.grafana-operator.svc.cluster.local:9090",
            "job"         = "grafana-operator",
            "instance"    = "grafana-operator-controller-manager",
            "namespace"   = "grafana-operator",
          },
        ]
        forward_to = [prometheus.remote_write.grafanacloud.receiver]
        scrape_interval = "10s"
        metrics_path = "/metrics"
      }

      // Scrape Alloy Internal Telemetry & Pipelines
      prometheus.scrape "alloy" {
        targets = [
          {
            "__address__" = "127.0.0.1:12345",
            "job"         = "alloy",
            "instance"    = "alloy-agent",
            "namespace"   = "alloy",
          },
        ]
        forward_to = [prometheus.remote_write.grafanacloud.receiver]
        scrape_interval = "10s"
        metrics_path = "/metrics"
      }

      // Remote Write to Grafana Cloud Prometheus
      prometheus.remote_write "grafanacloud" {
        endpoint {
          url = "https://prometheus-prod-43-prod-ap-south-1.grafana.net/api/prom/push"
          basic_auth {
            username = "2753177"
            password = env("GRAFANA_CLOUD_METRICS_TOKEN")
          }
        }
      }
