{{- range .Values.serviceAccounts }}
---
apiVersion: grafana.integreatly.org/v1beta1
kind: GrafanaServiceAccount
metadata:
  name: {{ .resourceName | default (.name | lower | replace " " "-") }}
  labels:
    {{- include "grafana-admin-platform.labels" $ | nindent 4 }}
    owner: {{ .owner | default "platform" }}
spec:
  instanceName: {{ .instanceName | default $.Values.grafana.name | default "grafanacloud-osttra" }}
  name: {{ .name }}
  role: {{ if or (eq .role "None") (not .role) }}Viewer{{ else }}{{ .role }}{{ end }}
  isDisabled: {{ .isDisabled | default false }}
  {{- if .secretName }}
  tokens:
    - name: {{ .tokenName | default (printf "%s-token" (.name | lower | replace " " "-")) }}
      expires: {{ .tokenExpires | default (now | dateModify "+8760h" | date "2006-01-02T15:04:05Z") | quote }}
      secretName: {{ .secretName | quote }}
  {{- end }}
{{- end }}
