{{- range .Values.datasources }}
---
apiVersion: grafana.integreatly.org/v1beta1
kind: GrafanaDatasource
metadata:
  name: {{ .name }}
  labels:
    {{- include "grafana-admin-platform.labels" $ | nindent 4 }}
spec:
  {{- include "grafana-admin-platform.instanceSelector" $ | nindent 2 }}
  datasource:
    {{- toYaml .datasource | nindent 4 }}
{{- end }}
