{{- if .Values.grafana.enabled }}
apiVersion: grafana.integreatly.org/v1beta1
kind: Grafana
metadata:
  name: {{ .Values.grafana.name | default "grafanacloud-osttra" }}
  labels:
    {{- include "grafana-admin-platform.labels" . | nindent 4 }}
    dashboards: {{ .Values.grafana.matchLabels.dashboards | default "osttra" }}
spec:
  external:
    url: {{ .Values.grafana.url | quote }}
    apiKey:
      name: {{ .Values.grafana.secretName | default "grafanacloud-credentials" | quote }}
      key: {{ .Values.grafana.secretKey | default "GRAFANA_API_KEY" | quote }}
{{- end }}
