{{- range .Values.serviceAccounts }}
---
apiVersion: grafana.integreatly.org/v1beta1
kind: GrafanaServiceAccount
metadata:
  name: {{ .resourceName | default (.name | lower | replace " " "-") }}
  labels:
    dashboards: {{ $.Values.grafana.instanceSelectorValue | default "osttra" }}
    grafana-admin-platform: managed
    owner: {{ .owner | default "platform" }}
spec:
  instanceName: {{ .instanceName | default $.Values.grafana.name | default "grafanacloud-osttra" }}
  name: {{ .name }}
  role: {{ if or (eq .role "None") (not .role) }}Viewer{{ else }}{{ .role }}{{ end }}
  isDisabled: {{ .isDisabled | default false }}
  {{- if .secretName }}
  tokens:
    - name: {{ .tokenName | default (printf "%s-token" (.name | lower | replace " " "-")) }}
      expires: {{ .tokenExpires | default "2027-08-22T00:00:00Z" | quote }}
      secretName: {{ .secretName | quote }}
  {{- end }}
{{- end }}
