{{- range .Values.folders }}
---
apiVersion: grafana.integreatly.org/v1beta1
kind: GrafanaFolder
metadata:
  name: {{ .uid }}-folder
  labels:
    {{- include "grafana-admin-platform.labels" $ | nindent 4 }}
spec:
  {{- include "grafana-admin-platform.instanceSelector" $ | nindent 2 }}
  uid: {{ .uid | quote }}
  title: {{ .title | quote }}
  {{- if .parentUid }}
  parentFolderUID: {{ .parentUid | quote }}
  {{- end }}
  {{- if .permissions }}
  permissions: |
    {
      "items": [
        {{- $items := list -}}
        {{- range .permissions -}}
          {{- if .role -}}
            {{- $items = append $items (printf "{\"role\": %s, \"permission\": %d}" (.role | quote) (int .permission)) -}}
          {{- else if .teamId -}}
            {{- $items = append $items (printf "{\"teamId\": %d, \"permission\": %d}" (int .teamId) (int .permission)) -}}
          {{- else if .userId -}}
            {{- $items = append $items (printf "{\"userId\": %d, \"permission\": %d}" (int .userId) (int .permission)) -}}
          {{- end -}}
        {{- end -}}
        {{- join "," $items }}
      ]
    }
  {{- end }}
{{- end }}
