{{- range .Values.alertRuleGroups }}
---
apiVersion: grafana.integreatly.org/v1beta1
kind: GrafanaAlertRuleGroup
metadata:
  name: {{ .name }}
  labels:
    {{- include "grafana-admin-platform.labels" $ | nindent 4 }}
    folder: {{ .folderUID }}
spec:
  {{- include "grafana-admin-platform.instanceSelector" $ | nindent 2 }}
  folderUID: {{ .folderUID | quote }}
  name: {{ .ruleGroupName | quote }}
  interval: {{ .interval | default "1m" | quote }}
  rules:
    {{- toYaml .rules | nindent 4 }}
{{- end }}
