folderUID: alerting-3tqje4zxqj67y
name: 1m-Evaluation-Group
interval: 1m
rules:
- uid: 4fd69e04-934e-5fdc-9371-773dc8f73139
  title: LinuxCPUHighUsage_Critical
  condition: threshold
  data:
  - refId: prometheus_math
    queryType: math
    relativeTimeRange:
      from: 0
      to: 0
    datasourceUid: __expr__
    model:
      datasource:
        IsPrunable: false
        access: ''
        apiVersion: ''
        basicAuth: false
        basicAuthUser: ''
        created: '0001-01-01T00:00:00Z'
        database: ''
        id: -100
        isDefault: false
        jsonData: {}
        name: __expr__
        readOnly: false
        secureJsonData: {}
        type: __expr__
        uid: __expr__
        updated: '0001-01-01T00:00:00Z'
        url: ''
        user: ''
        withCredentials: false
      expression: is_number($query) || is_nan($query) || is_inf($query)
      intervalMs: 1000
      maxDataPoints: 43200
      refId: prometheus_math
      type: math
  - refId: query
    queryType: prometheus
    relativeTimeRange:
      from: 660
      to: 60
    datasourceUid: grafanacloud-prom
    model:
      datasource:
        type: prometheus
        uid: grafanacloud-prom
      expr: sum without (mode) (avg without (cpu) (rate(node_cpu_seconds_total{mode!~"idle|iowait"}[5m])))
        * 100 > 90
      instant: true
      intervalMs: 1000
      maxDataPoints: 43200
      range: false
      refId: query
  - refId: threshold
    queryType: threshold
    relativeTimeRange:
      from: 0
      to: 0
    datasourceUid: __expr__
    model:
      conditions:
      - evaluator:
          params:
          - 0
          type: gt
      datasource:
        IsPrunable: false
        access: ''
        apiVersion: ''
        basicAuth: false
        basicAuthUser: ''
        created: '0001-01-01T00:00:00Z'
        database: ''
        id: -100
        isDefault: false
        jsonData: {}
        name: __expr__
        readOnly: false
        secureJsonData: {}
        type: __expr__
        uid: __expr__
        updated: '0001-01-01T00:00:00Z'
        url: ''
        user: ''
        withCredentials: false
      expression: prometheus_math
      intervalMs: 1000
      maxDataPoints: 43200
      refId: threshold
      type: threshold
  for: 5m
  noDataState: OK
  execErrState: OK
  isPaused: true
  labels:
    __converted_prometheus_rule__: 'true'
    os: linux
    severity: critical
  annotations:
    description: CPU utilization has exceeded 90% for 5 minutes.
    summary: Linux CPU Critical >90% on {{ $labels.instance }}
- uid: 2b7665bd-656a-584c-b82b-c152330ecae8
  title: LinuxCPUHighUsage_Warning
  condition: threshold
  data:
  - refId: query
    queryType: prometheus
    relativeTimeRange:
      from: 660
      to: 60
    datasourceUid: grafanacloud-prom
    model:
      datasource:
        type: prometheus
        uid: grafanacloud-prom
      expr: sum without (mode) (avg without (cpu) (rate(node_cpu_seconds_total{mode!~"idle|iowait"}[5m])))
        * 100 > 80
      instant: true
      intervalMs: 1000
      maxDataPoints: 43200
      range: false
      refId: query
  - refId: prometheus_math
    queryType: math
    relativeTimeRange:
      from: 0
      to: 0
    datasourceUid: __expr__
    model:
      datasource:
        IsPrunable: false
        access: ''
        apiVersion: ''
        basicAuth: false
        basicAuthUser: ''
        created: '0001-01-01T00:00:00Z'
        database: ''
        id: -100
        isDefault: false
        jsonData: {}
        name: __expr__
        readOnly: false
        secureJsonData: {}
        type: __expr__
        uid: __expr__
        updated: '0001-01-01T00:00:00Z'
        url: ''
        user: ''
        withCredentials: false
      expression: is_number($query) || is_nan($query) || is_inf($query)
      intervalMs: 1000
      maxDataPoints: 43200
      refId: prometheus_math
      type: math
  - refId: threshold
    queryType: threshold
    relativeTimeRange:
      from: 0
      to: 0
    datasourceUid: __expr__
    model:
      conditions:
      - evaluator:
          params:
          - 0
          type: gt
      datasource:
        IsPrunable: false
        access: ''
        apiVersion: ''
        basicAuth: false
        basicAuthUser: ''
        created: '0001-01-01T00:00:00Z'
        database: ''
        id: -100
        isDefault: false
        jsonData: {}
        name: __expr__
        readOnly: false
        secureJsonData: {}
        type: __expr__
        uid: __expr__
        updated: '0001-01-01T00:00:00Z'
        url: ''
        user: ''
        withCredentials: false
      expression: prometheus_math
      intervalMs: 1000
      maxDataPoints: 43200
      refId: threshold
      type: threshold
  for: 5m
  noDataState: OK
  execErrState: OK
  isPaused: true
  labels:
    __converted_prometheus_rule__: 'true'
    os: linux
    severity: warning
  annotations:
    description: CPU utilization has exceeded 80% for 5 minutes.
    summary: Linux CPU Warning >80% on {{ $labels.instance }}
- uid: a66daeeb-fae5-59dc-9159-60b855eba792
  title: WindowsCPUHighUsage_Warning
  condition: threshold
  data:
  - refId: query
    queryType: prometheus
    relativeTimeRange:
      from: 660
      to: 60
    datasourceUid: grafanacloud-prom
    model:
      datasource:
        type: prometheus
        uid: grafanacloud-prom
      expr: 100 - (avg without (mode, core) (rate(windows_cpu_time_total{mode="idle"}[5m]))
        * 100) > 80
      instant: true
      intervalMs: 1000
      maxDataPoints: 43200
      range: false
      refId: query
  - refId: prometheus_math
    queryType: math
    relativeTimeRange:
      from: 0
      to: 0
    datasourceUid: __expr__
    model:
      datasource:
        IsPrunable: false
        access: ''
        apiVersion: ''
        basicAuth: false
        basicAuthUser: ''
        created: '0001-01-01T00:00:00Z'
        database: ''
        id: -100
        isDefault: false
        jsonData: {}
        name: __expr__
        readOnly: false
        secureJsonData: {}
        type: __expr__
        uid: __expr__
        updated: '0001-01-01T00:00:00Z'
        url: ''
        user: ''
        withCredentials: false
      expression: is_number($query) || is_nan($query) || is_inf($query)
      intervalMs: 1000
      maxDataPoints: 43200
      refId: prometheus_math
      type: math
  - refId: threshold
    queryType: threshold
    relativeTimeRange:
      from: 0
      to: 0
    datasourceUid: __expr__
    model:
      conditions:
      - evaluator:
          params:
          - 0
          type: gt
      datasource:
        IsPrunable: false
        access: ''
        apiVersion: ''
        basicAuth: false
        basicAuthUser: ''
        created: '0001-01-01T00:00:00Z'
        database: ''
        id: -100
        isDefault: false
        jsonData: {}
        name: __expr__
        readOnly: false
        secureJsonData: {}
        type: __expr__
        uid: __expr__
        updated: '0001-01-01T00:00:00Z'
        url: ''
        user: ''
        withCredentials: false
      expression: prometheus_math
      intervalMs: 1000
      maxDataPoints: 43200
      refId: threshold
      type: threshold
  for: 5m
  noDataState: OK
  execErrState: OK
  isPaused: true
  labels:
    __converted_prometheus_rule__: 'true'
    os: windows
    severity: warning
  annotations:
    description: CPU utilization has exceeded 80% for 5 minutes.
    summary: Windows CPU Warning >80% on {{ $labels.instance }}
- uid: b7646696-6d43-56e1-a422-8da003917d45
  title: WindowsCPUHighUsage_Warning
  condition: threshold
  data:
  - refId: query
    queryType: prometheus
    relativeTimeRange:
      from: 660
      to: 60
    datasourceUid: grafanacloud-prom
    model:
      datasource:
        type: prometheus
        uid: grafanacloud-prom
      expr: 100 - (avg without (mode, core) (rate(windows_cpu_time_total{mode="idle"}[5m]))
        * 100) > 80
      instant: true
      intervalMs: 1000
      maxDataPoints: 43200
      range: false
      refId: query
  - refId: prometheus_math
    queryType: math
    relativeTimeRange:
      from: 0
      to: 0
    datasourceUid: __expr__
    model:
      datasource:
        IsPrunable: false
        access: ''
        apiVersion: ''
        basicAuth: false
        basicAuthUser: ''
        created: '0001-01-01T00:00:00Z'
        database: ''
        id: -100
        isDefault: false
        jsonData: {}
        name: __expr__
        readOnly: false
        secureJsonData: {}
        type: __expr__
        uid: __expr__
        updated: '0001-01-01T00:00:00Z'
        url: ''
        user: ''
        withCredentials: false
      expression: is_number($query) || is_nan($query) || is_inf($query)
      intervalMs: 1000
      maxDataPoints: 43200
      refId: prometheus_math
      type: math
  - refId: threshold
    queryType: threshold
    relativeTimeRange:
      from: 0
      to: 0
    datasourceUid: __expr__
    model:
      conditions:
      - evaluator:
          params:
          - 0
          type: gt
      datasource:
        IsPrunable: false
        access: ''
        apiVersion: ''
        basicAuth: false
        basicAuthUser: ''
        created: '0001-01-01T00:00:00Z'
        database: ''
        id: -100
        isDefault: false
        jsonData: {}
        name: __expr__
        readOnly: false
        secureJsonData: {}
        type: __expr__
        uid: __expr__
        updated: '0001-01-01T00:00:00Z'
        url: ''
        user: ''
        withCredentials: false
      expression: prometheus_math
      intervalMs: 1000
      maxDataPoints: 43200
      refId: threshold
      type: threshold
  for: 5m
  noDataState: OK
  execErrState: OK
  isPaused: true
  labels:
    __converted_prometheus_rule__: 'true'
    os: windows
    severity: warning
  annotations:
    description: CPU utilization has exceeded 80% for 5 minutes.
    summary: Windows CPU Warning >80% on {{ $labels.instance }}
