folderUID: alerting-3tqje4zxqj67y
name: integrations-linux-node-custom
interval: 1m
rules:
- uid: 2a8ce8b7-46b9-58fa-8d74-792dc152e742
  title: LinuxFilesystemAlmostOutOfSpace_Critical
  condition: threshold
  data:
  - refId: query
    queryType: prometheus
    relativeTimeRange:
      from: 660
      to: 60
    datasourceUid: grafanacloud-prom
    model:
      datasource:
        type: prometheus
        uid: grafanacloud-prom
      expr: (node_filesystem_avail_bytes{device!~".*snapshot.*",fstype!="",mountpoint!="/boot"}
        / node_filesystem_size_bytes{device!~".*snapshot.*",fstype!="",mountpoint!="/boot"}
        * 100 < 5 and node_filesystem_readonly{device!~".*snapshot.*",fstype!="",mountpoint!="/boot"}
        == 0)
      instant: true
      intervalMs: 1000
      maxDataPoints: 43200
      range: false
      refId: query
  - refId: prometheus_math
    queryType: math
    relativeTimeRange:
      from: 0
      to: 0
    datasourceUid: __expr__
    model:
      datasource:
        IsPrunable: false
        access: ''
        apiVersion: ''
        basicAuth: false
        basicAuthUser: ''
        created: '0001-01-01T00:00:00Z'
        database: ''
        id: -100
        isDefault: false
        jsonData: {}
        name: __expr__
        readOnly: false
        secureJsonData: {}
        type: __expr__
        uid: __expr__
        updated: '0001-01-01T00:00:00Z'
        url: ''
        user: ''
        withCredentials: false
      expression: is_number($query) || is_nan($query) || is_inf($query)
      intervalMs: 1000
      maxDataPoints: 43200
      refId: prometheus_math
      type: math
  - refId: threshold
    queryType: threshold
    relativeTimeRange:
      from: 0
      to: 0
    datasourceUid: __expr__
    model:
      conditions:
      - evaluator:
          params:
          - 0
          type: gt
      datasource:
        IsPrunable: false
        access: ''
        apiVersion: ''
        basicAuth: false
        basicAuthUser: ''
        created: '0001-01-01T00:00:00Z'
        database: ''
        id: -100
        isDefault: false
        jsonData: {}
        name: __expr__
        readOnly: false
        secureJsonData: {}
        type: __expr__
        uid: __expr__
        updated: '0001-01-01T00:00:00Z'
        url: ''
        user: ''
        withCredentials: false
      expression: prometheus_math
      intervalMs: 1000
      maxDataPoints: 43200
      refId: threshold
      type: threshold
  for: 15m
  noDataState: OK
  execErrState: OK
  isPaused: true
  labels:
    __converted_prometheus_rule__: 'true'
    os: linux
    severity: critical
  annotations:
    description: Disk space is more than 95% full for 15 minutes.
    summary: Linux Filesystem Critical >95% utilized on {{ $labels.instance }}
- uid: 7444ebaf-a539-5d59-a546-3c2b85f2d324
  title: LinuxFilesystemAlmostOutOfSpace_Warning
  condition: threshold
  data:
  - refId: query
    queryType: prometheus
    relativeTimeRange:
      from: 660
      to: 60
    datasourceUid: grafanacloud-prom
    model:
      datasource:
        type: prometheus
        uid: grafanacloud-prom
      expr: (node_filesystem_avail_bytes{device!~".*snapshot.*",fstype!="",mountpoint!="/boot"}
        / node_filesystem_size_bytes{device!~".*snapshot.*",fstype!="",mountpoint!="/boot"}
        * 100 < 10 and node_filesystem_readonly{device!~".*snapshot.*",fstype!="",mountpoint!="/boot"}
        == 0)
      instant: true
      intervalMs: 1000
      maxDataPoints: 43200
      range: false
      refId: query
  - refId: prometheus_math
    queryType: math
    relativeTimeRange:
      from: 0
      to: 0
    datasourceUid: __expr__
    model:
      datasource:
        IsPrunable: false
        access: ''
        apiVersion: ''
        basicAuth: false
        basicAuthUser: ''
        created: '0001-01-01T00:00:00Z'
        database: ''
        id: -100
        isDefault: false
        jsonData: {}
        name: __expr__
        readOnly: false
        secureJsonData: {}
        type: __expr__
        uid: __expr__
        updated: '0001-01-01T00:00:00Z'
        url: ''
        user: ''
        withCredentials: false
      expression: is_number($query) || is_nan($query) || is_inf($query)
      intervalMs: 1000
      maxDataPoints: 43200
      refId: prometheus_math
      type: math
  - refId: threshold
    queryType: threshold
    relativeTimeRange:
      from: 0
      to: 0
    datasourceUid: __expr__
    model:
      conditions:
      - evaluator:
          params:
          - 0
          type: gt
      datasource:
        IsPrunable: false
        access: ''
        apiVersion: ''
        basicAuth: false
        basicAuthUser: ''
        created: '0001-01-01T00:00:00Z'
        database: ''
        id: -100
        isDefault: false
        jsonData: {}
        name: __expr__
        readOnly: false
        secureJsonData: {}
        type: __expr__
        uid: __expr__
        updated: '0001-01-01T00:00:00Z'
        url: ''
        user: ''
        withCredentials: false
      expression: prometheus_math
      intervalMs: 1000
      maxDataPoints: 43200
      refId: threshold
      type: threshold
  for: 15m
  noDataState: OK
  execErrState: OK
  isPaused: true
  labels:
    __converted_prometheus_rule__: 'true'
    os: linux
    severity: warning
  annotations:
    description: Disk space is more than 90% full for 15 minutes.
    summary: Linux Filesystem Warning >90% utilized on {{ $labels.instance }}
- uid: c6b06bbf-5584-583e-8e47-995ebbfed4c2
  title: LinuxMemoryHighUtilization_Warning
  condition: threshold
  data:
  - refId: query
    queryType: prometheus
    relativeTimeRange:
      from: 660
      to: 60
    datasourceUid: grafanacloud-prom
    model:
      datasource:
        type: prometheus
        uid: grafanacloud-prom
      expr: 100 - (node_memory_MemAvailable_bytes / node_memory_MemTotal_bytes * 100)
        > 90
      instant: true
      intervalMs: 1000
      maxDataPoints: 43200
      range: false
      refId: query
  - refId: prometheus_math
    queryType: math
    relativeTimeRange:
      from: 0
      to: 0
    datasourceUid: __expr__
    model:
      datasource:
        IsPrunable: false
        access: ''
        apiVersion: ''
        basicAuth: false
        basicAuthUser: ''
        created: '0001-01-01T00:00:00Z'
        database: ''
        id: -100
        isDefault: false
        jsonData: {}
        name: __expr__
        readOnly: false
        secureJsonData: {}
        type: __expr__
        uid: __expr__
        updated: '0001-01-01T00:00:00Z'
        url: ''
        user: ''
        withCredentials: false
      expression: is_number($query) || is_nan($query) || is_inf($query)
      intervalMs: 1000
      maxDataPoints: 43200
      refId: prometheus_math
      type: math
  - refId: threshold
    queryType: threshold
    relativeTimeRange:
      from: 0
      to: 0
    datasourceUid: __expr__
    model:
      conditions:
      - evaluator:
          params:
          - 0
          type: gt
      datasource:
        IsPrunable: false
        access: ''
        apiVersion: ''
        basicAuth: false
        basicAuthUser: ''
        created: '0001-01-01T00:00:00Z'
        database: ''
        id: -100
        isDefault: false
        jsonData: {}
        name: __expr__
        readOnly: false
        secureJsonData: {}
        type: __expr__
        uid: __expr__
        updated: '0001-01-01T00:00:00Z'
        url: ''
        user: ''
        withCredentials: false
      expression: prometheus_math
      intervalMs: 1000
      maxDataPoints: 43200
      refId: threshold
      type: threshold
  for: 15m
  noDataState: OK
  execErrState: OK
  isPaused: true
  labels:
    __converted_prometheus_rule__: 'true'
    os: linux
    severity: warning
  annotations:
    description: Physical memory utilization has exceeded 90% for 15 minutes.
    summary: Linux Memory Warning >90% on {{ $labels.instance }}
- uid: bb648d90-45c3-5bd8-958f-3d17dac941bb
  title: LinuxNodeUnreachable
  condition: threshold
  data:
  - refId: query
    queryType: prometheus
    relativeTimeRange:
      from: 660
      to: 60
    datasourceUid: grafanacloud-prom
    model:
      datasource:
        type: prometheus
        uid: grafanacloud-prom
      expr: up{job=~".*node.*"} == 0
      instant: true
      intervalMs: 1000
      maxDataPoints: 43200
      range: false
      refId: query
  - refId: prometheus_math
    queryType: math
    relativeTimeRange:
      from: 0
      to: 0
    datasourceUid: __expr__
    model:
      datasource:
        IsPrunable: false
        access: ''
        apiVersion: ''
        basicAuth: false
        basicAuthUser: ''
        created: '0001-01-01T00:00:00Z'
        database: ''
        id: -100
        isDefault: false
        jsonData: {}
        name: __expr__
        readOnly: false
        secureJsonData: {}
        type: __expr__
        uid: __expr__
        updated: '0001-01-01T00:00:00Z'
        url: ''
        user: ''
        withCredentials: false
      expression: is_number($query) || is_nan($query) || is_inf($query)
      intervalMs: 1000
      maxDataPoints: 43200
      refId: prometheus_math
      type: math
  - refId: threshold
    queryType: threshold
    relativeTimeRange:
      from: 0
      to: 0
    datasourceUid: __expr__
    model:
      conditions:
      - evaluator:
          params:
          - 0
          type: gt
      datasource:
        IsPrunable: false
        access: ''
        apiVersion: ''
        basicAuth: false
        basicAuthUser: ''
        created: '0001-01-01T00:00:00Z'
        database: ''
        id: -100
        isDefault: false
        jsonData: {}
        name: __expr__
        readOnly: false
        secureJsonData: {}
        type: __expr__
        uid: __expr__
        updated: '0001-01-01T00:00:00Z'
        url: ''
        user: ''
        withCredentials: false
      expression: prometheus_math
      intervalMs: 1000
      maxDataPoints: 43200
      refId: threshold
      type: threshold
  for: 10m
  noDataState: OK
  execErrState: OK
  isPaused: true
  labels:
    __converted_prometheus_rule__: 'true'
    os: linux
    severity: critical
  annotations:
    description: Node exporter on {{ $labels.instance }} has been unreachable for
      10 minutes.
    summary: Linux node unreachable {{ $labels.instance }}
- uid: d6b46dc4-5704-5ca7-b5aa-6b2768bfb553
  title: LinuxNodeHasRebooted
  condition: threshold
  data:
  - refId: query
    queryType: prometheus
    relativeTimeRange:
      from: 660
      to: 60
    datasourceUid: grafanacloud-prom
    model:
      datasource:
        type: prometheus
        uid: grafanacloud-prom
      expr: (time() - node_boot_time_seconds) < 3600
      instant: true
      intervalMs: 1000
      maxDataPoints: 43200
      range: false
      refId: query
  - refId: prometheus_math
    queryType: math
    relativeTimeRange:
      from: 0
      to: 0
    datasourceUid: __expr__
    model:
      datasource:
        IsPrunable: false
        access: ''
        apiVersion: ''
        basicAuth: false
        basicAuthUser: ''
        created: '0001-01-01T00:00:00Z'
        database: ''
        id: -100
        isDefault: false
        jsonData: {}
        name: __expr__
        readOnly: false
        secureJsonData: {}
        type: __expr__
        uid: __expr__
        updated: '0001-01-01T00:00:00Z'
        url: ''
        user: ''
        withCredentials: false
      expression: is_number($query) || is_nan($query) || is_inf($query)
      intervalMs: 1000
      maxDataPoints: 43200
      refId: prometheus_math
      type: math
  - refId: threshold
    queryType: threshold
    relativeTimeRange:
      from: 0
      to: 0
    datasourceUid: __expr__
    model:
      conditions:
      - evaluator:
          params:
          - 0
          type: gt
      datasource:
        IsPrunable: false
        access: ''
        apiVersion: ''
        basicAuth: false
        basicAuthUser: ''
        created: '0001-01-01T00:00:00Z'
        database: ''
        id: -100
        isDefault: false
        jsonData: {}
        name: __expr__
        readOnly: false
        secureJsonData: {}
        type: __expr__
        uid: __expr__
        updated: '0001-01-01T00:00:00Z'
        url: ''
        user: ''
        withCredentials: false
      expression: prometheus_math
      intervalMs: 1000
      maxDataPoints: 43200
      refId: threshold
      type: threshold
  for: 30m
  noDataState: OK
  execErrState: OK
  isPaused: true
  labels:
    __converted_prometheus_rule__: 'true'
    os: linux
    severity: info
  annotations:
    description: Node {{ $labels.instance }} has rebooted within the last 60 minutes.
    summary: Linux node rebooted recently {{ $labels.instance }}
