apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: grafana-admin-platform
  namespace: flux-system
spec:
  interval: 1m
  url: https://github.com/cosmicsatish/grafana-admin-platform.git
  ref:
    branch: main
  ignore: |
    /README.md
    /.github/
