# Values for the official Grafana Operator chart.
leaderElect: true
logging:
  level: info
  encoder: json
# Periodic resync interval for automatic drift detection & self-healing
resyncPeriod: 30s
crds:
  immutable: false
