folderUID: alerting-rxiy1eec9ooy
name: crds_alert_every_30_min
interval: 1m
rules:
- uid: bd82bf4c-fac9-5ce6-8207-8e6b7dee407a
  title: CrdsProdDbCpuUtilization80
  condition: threshold
  data:
  - refId: query
    queryType: prometheus
    relativeTimeRange:
      from: 660
      to: 60
    datasourceUid: grafanacloud-prom
    model:
      datasource:
        type: prometheus
        uid: grafanacloud-prom
      expr: aws_rds_cpuutilization_average{account_id="805285833067", dimension_DBInstanceIdentifier=~"osttra-crds-.*"}
        > 80.0
      instant: true
      intervalMs: 1000
      maxDataPoints: 43200
      range: false
      refId: query
  - refId: prometheus_math
    queryType: math
    relativeTimeRange:
      from: 0
      to: 0
    datasourceUid: __expr__
    model:
      datasource:
        IsPrunable: false
        access: ''
        apiVersion: ''
        basicAuth: false
        basicAuthUser: ''
        created: '0001-01-01T00:00:00Z'
        database: ''
        id: -100
        isDefault: false
        jsonData: {}
        name: __expr__
        readOnly: false
        secureJsonData: {}
        type: __expr__
        uid: __expr__
        updated: '0001-01-01T00:00:00Z'
        url: ''
        user: ''
        withCredentials: false
      expression: is_number($query) || is_nan($query) || is_inf($query)
      intervalMs: 1000
      maxDataPoints: 43200
      refId: prometheus_math
      type: math
  - refId: threshold
    queryType: threshold
    relativeTimeRange:
      from: 0
      to: 0
    datasourceUid: __expr__
    model:
      conditions:
      - evaluator:
          params:
          - 0
          type: gt
      datasource:
        IsPrunable: false
        access: ''
        apiVersion: ''
        basicAuth: false
        basicAuthUser: ''
        created: '0001-01-01T00:00:00Z'
        database: ''
        id: -100
        isDefault: false
        jsonData: {}
        name: __expr__
        readOnly: false
        secureJsonData: {}
        type: __expr__
        uid: __expr__
        updated: '0001-01-01T00:00:00Z'
        url: ''
        user: ''
        withCredentials: false
      expression: prometheus_math
      intervalMs: 1000
      maxDataPoints: 43200
      refId: threshold
      type: threshold
  for: 30m
  noDataState: OK
  execErrState: OK
  isPaused: true
  labels:
    Application: CRDS
    Environment: Production
    Organization: Osttra
    __converted_prometheus_rule__: 'true'
    severity: '{{ if ge $value 85.0 }}critical{{ else }}warning{{ end }}'
  annotations:
    description: 'Metric value is at {{ printf "%.2f" $value }} (Severity: {{ if ge
      $value 85.0 }}CRITICAL{{ else }}WARNING{{ end }}).'
    summary: CrdsProdDbCpuUtilization80 high threshold reached on {{ $labels.instance
      }}
