datasources:
  - name: loki-lbac-datasource
    datasource:
      name: "loki-lbac"
      type: "loki"
      access: "proxy"
      url: "https://logs-prod-006.grafana.net"
      uid: "ffvme66npet4wf"
      isDefault: false
      editable: true
      jsonData:
        httpHeaderName1: "X-Scope-OrgID"
        maxLines: 5000
