serviceAccounts:
  - name: config-reconciler
    role: Editor
    secretName: config-reconciler-token

  - name: config-reconciler-readonly-for-testing
    role: None
    secretName: config-reconciler-readonly-token

  - name: grafana-operator
    resourceName: grafana-operator-sa
    role: Editor
    secretName: grafana-operator-token

  - name: grafana-resource-provisioner
    role: Viewer
    secretName: grafana-resource-provisioner-token

  - name: alert-provisioning-writer
    role: None
    secretName: alert-provisioning-writer-token

  - name: alerts-reader-ITS-30152
    resourceName: alerts-reader-its-30152
    role: None
    secretName: alerts-reader-its-30152-token

  - name: grafana-mcp-server
    role: Viewer
    secretName: grafana-mcp-server-token

  - name: MCP Grafana
    resourceName: mcp-grafana
    role: None
    secretName: mcp-grafana-token

  - name: API
    resourceName: api-integration
    role: None
    secretName: api-integration-token

  - name: apigee-logs-grafana-app
    role: Viewer
    secretName: apigee-logs-token

  - name: markitserv-datasource-viewer-app
    role: Viewer
    secretName: markitserv-viewer-token

  - name: screenly-test-app
    role: Viewer
    secretName: screenly-app-token

  - name: svc-api-gw
    role: Viewer
    secretName: svc-api-gw-token

  - name: svc-call-grafana-api-toc
    role: Admin
    owner: toc
    secretName: svc-call-toc-token

  - name: toc-tools
    role: Viewer
    owner: toc
    secretName: toc-tools-token

  - name: winops-automation
    role: Viewer
    owner: sysadmin
    secretName: winops-automation-token

  - name: log-downloader
    role: Viewer
    secretName: log-downloader-token

  - name: Satish-Personal-Token
    resourceName: satish-personal-token
    role: Admin
    owner: satish
    secretName: satish-personal-token

  - name: Rama_personal_account
    resourceName: rama-personal-account
    role: None
    owner: rama
    secretName: rama-personal-token
