datasources:
  - name: grafanacloud-cosmicsatish-logs-lbac-datasource
    datasource:
      name: "grafanacloud-cosmicsatish-logs-lbac"
      type: "loki"
      access: "proxy"
      url: "https://logs-prod-028.grafana.net"
      uid: "grafanacloud-logs-lbac"
      isDefault: false
      editable: true
      basicAuth: true
      basicAuthUser: "1372265"
      jsonData:
        derivedFields:
          - datasourceUid: "grafanacloud-traces"
            matcherRegex: '[tT]race_?[iI][dD]"?[:=]"?(\\w+)'
            matcherType: "regex"
            name: "traceID"
            url: "${__value.raw}"
          - datasourceUid: "grafanacloud-traces"
            matcherRegex: '[tT]race_?[iI][dD]'
            matcherType: "label"
            name: "traceID (field)"
            url: "${__value.raw}"
        streamingEnabled:
          search: true
        timeout: "300"
        maxLines: 5000
        httpHeaderName1: "X-Scope-OrgID"
